export const curatedCountries = [
    "afghanistan",
    "albania",
    "algeria",
    "armenia",
    "azerbaijan",
    "argentina",
    "aruba",
    "austria",
    "bahamas",
    "australia",
    "belarus",
    "bangladesh",
    "belgium",
    "belize",
    "bermuda",
    "benin",
    "bhutan",
    "bolivia",
    "brazil",
    "bulgaria",
    "cameroon",
    "burkina faso",
    "cape verde",
    "cayman islands",
    "cambodia",
    "chad",
    "chile",
    "colombia",
    "costa rica",
    "china",
    "congo",
    "croatia",
    "cuba",
    "czech republic",
    "cyprus",
    "denmark",
    "dominica",
    "dominican republic",
    "egypt",
    "ecuador",
    "el salvador",
    "estonia",
    "ethiopia",
    "faroe islands",
    "finland",
    "faroe islands",
    "france",
    "fiji",
    "gibraltar",
    "ghana",
    "gambia",
    "georgia",
    "germany",
    "greenland",
    "guatemala",
    "greece",
    "haiti",
    "guinea",
    "hong kong",
    "india",
    "honduras",
    "iceland",
    "hungary",
    "indonesia",
    "iran",
    "iraq",
    "jamaica",
    "ireland",
    "japan",
    "jersey",
    "israel",
    "italy",
    "jordan",
    "kenya",
    "kuwait",
    "laos",
    "kazakhstan",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "lithuania",
    "liechtenstein",
    "luxembourg",
    "madagascar",
    "macedonia",
    "macau",
    "malaysia",
    "malta",
    "malawi",
    "mali",
    "monaco",
    "moldova",
    "mongolia",
    "mexico",
    "montenegro",
    "morocco",
    "mauritius",
    "montserrat",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "nigeria",
    "niger",
    "oman",
    "pakistan",
    "paraguay",
    "panama",
    "palestine",
    "portugal",
    "peru",
    "philippines",
    "norway",
    "russia",
    "reunion",
    "poland",
    "rwanda",
    "qatar",
    "satellite",
    "san marino",
    "saudi arabia",
    "puerto rico",
    "serbia",
    "romania",
    "senegal",
    "seychelles",
    "sierra leone",
    "singapore",
    "slovakia",
    "slovenia",
    "sri lanka",
    "spain",
    "st lucia",
    "south africa",
    "st. lucia",
    "south korea",
    "sudan",
    "switzerland",
    "syria",
    "sweden",
    "taiwan",
    "tanzania",
    "thailand",
    "tunisia",
    "turkey",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "uruguay",
    "uzbekistan",
    "yemen",
    "uganda",
    "vietnam",
    "zambia",
    "venezuela",
    "zimbabwe"
  ]