export const curatedCountries = [
    "algeria",
    "armenia",
    "azerbaijan",
    "argentina",
    "austria",
    "bahamas",
    "australia",
    "belarus",
    "bangladesh",
    "belgium",
    "belize", 
    "benin",
    "bhutan",
    "bolivia",
    "brazil",
    "bulgaria",
    "cameroon",
    "burkina faso",
    "cape verde",
    "cambodia",
    "chile",
    "colombia",
    "costa rica",
    "china",
    "croatia",
    "cuba",
    "czech republic",
    "cyprus",
    "denmark",
    "dominican republic",
    "egypt",
    "ecuador",
    "el salvador",
    "estonia",
    "ethiopia",
    "finland",
    "france",
    "gibraltar",
    "ghana",
    "gambia",
    "germany",
    "greenland",
    "guatemala",
    "greece",
    "haiti",
    "hong kong",
    "india",
    "honduras",
    "iceland",
    "hungary",
    "indonesia",
    "iran",
    "iraq",
    "jamaica",
    "ireland",
    "japan",
    "israel",
    "italy",
    "kenya",
    "kuwait",
    "laos",
    "kazakhstan",
    "latvia",
    "lebanon",
    "lithuania",
    "luxembourg",
    "madagascar",
    "macedonia",
    "macau",
    "malaysia",
    "malta",
    "malawi",
    "mali",
    "monaco",
    "mongolia",
    "mexico",
    "montenegro",
    "morocco",
    "mauritius",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "nigeria",
    "niger",
    "oman",
    "pakistan",
    "paraguay",
    "panama",
    "palestine",
    "portugal",
    "peru",
    "philippines",
    "norway",
    "russia",
    "poland",
    "rwanda",
    "saudi arabia",
    "puerto rico",
    "serbia",
    "romania",
    "senegal",
    "seychelles",
    "singapore",
    "slovakia",
    "slovenia",
    "sri lanka",
    "spain",
    "south africa",
    "south korea",
    "sudan",
    "switzerland",
    "sweden",
    "taiwan",
    "tanzania",
    "thailand",
    "tunisia",
    "turkey",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "uruguay",
    "uzbekistan",
    "uganda",
    "vietnam",
    "zambia",
    "venezuela",
    "zimbabwe"
  ]